export type RootStackParamList = {
  Splash: undefined;
  LanguageSelection: undefined;
  Selection: undefined;
  UserLogin: undefined;
  AdminLogin: undefined;
  Signup1: undefined;
  Signup2: {
    firstName: string;
    middleName: string;
    lastName: string;
    homeNumber: string;
    wardNumber: string;
    localityName: string;
  };
  Signup3: {
    firstName: string;
    middleName: string;
    lastName: string;
    homeNumber: string;
    wardNumber: string;
    localityName: string;
    profilePic: string;
    idType: string;
    idNumber: string;
    idPhoto: string;
  };
  Signup4: {
    firstName: string;
    middleName: string;
    lastName: string;
    homeNumber: string;
    wardNumber: string;
    localityName: string;
    profilePic: string;
    idType: string;
    idNumber: string;
    idPhoto: string;
    phone: string;
    email: string;
    otp: string;
    password: string;
  };
  Home: { role: 'user' | 'admin' };
  AdminDashboard: undefined;
  Profile: undefined;
  AdminProfile: undefined;
  ManageUsers: undefined;
  Feedback: undefined;
  Rewards: undefined;
  ReportHistory: undefined;
  Support: undefined;
  RewardHistory: undefined;
  PointsRedemption: undefined;
  ReportWaste: undefined;
  AdminWasteReview: undefined;
  AdminWasteHistory: undefined;
  CustomPickup: undefined;
  AdminCustomPickup: undefined;
  TruckManagement: undefined;
  TruckLocation: undefined;
  Badges: undefined;
  Leaderboard: undefined;
};
